tm_dbt_snowflake:
  outputs:
    dev:
      account: bta69289.us-east-1
      database: CRYPTO_DB_DEV
      password: xxxxxxxxxxxxxxx
      role: ACCOUNTADMIN
      schema: DATA_HUB
      threads: 1
      type: snowflake
      user: tm_di_admin_acct
      warehouse: TM_DI_WH
  target: dev
