tm_dbt_snowflake:
  outputs:
    dev:
      account: bta69289.us-east-1
      database: CRYPTO_DB_DEV
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: DATA_HUB
      threads: 5
      type: snowflake
      user: tm_di_admin_acct
      warehouse: TM_DI_WH
    ci:
      account: bta69289.us-east-1
      database: CRYPTO_DB_DEV
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: CI
      threads: 5
      type: snowflake
      user: tm_di_admin_acct
      warehouse: TM_DI_WH
  target: dev
