tm_dbt_snowflake:
  outputs:
    dev:
      account: bta69289.us-east-1
      database: CRYPTO_DB_DEV
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: DATA_HUB
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
  target: dev
