name: Deploy DBT docs to Github Pages

on:
  push:
    branches:
      - development
    # paths:
    #   #only run if there are changes in dbt folder
    #   - "dbt/**"

env:
  ENVIRONMENT: development
        #   env:  # Pass the secret as an environment variable
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

#Sets permissions of the GITHUB_TOKEN to allow deployment to Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Howerver, do NOT cancel in-progress runs as we want to allow these production deployments to complete.

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying everytime
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Create credentials file from secret
        run: |
          mkdir -p ./credentials
          echo "${{ secrets.DBT_SNOWFLAKE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./credentials/dbt-snowflake-credentials-sa.json
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: token-metrics-389311  # Replace with your GCP Project ID
      # Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=./credentials/dbt-snowflake-credentials-sa.json
      # - name: Get dbt Manifest
      #   run: |
      #     mkdir state
      #     gcloud storage cp gs://tm-dbt-snowflake/${ENVIRONMENT}/manifest.json ./state/manifest.json || echo "File does not exist. Skipping..."
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake==1.7.5

      - name: Generate dbt docs
        id: docs 
        run: |
          dbt deps
          dbt docs generate --target-path dbt-docs --target ci
      
      - name: Upload DBT docs to Page artifact
        id: build
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbt/dbt-docs
          name: dbt-docs
      - name: Publish DBT docs to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: dbt-docs

  