name: Deploy to Development

on:
  push:
    branches:
      - development

env:
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  # SNOWFLAKE_USER: ${{ env.SNOWFLAKE_USER }}
  # SNOWFLAKE_WAREHOUSE: ${{ env.SNOWFLAKE_WAREHOUSE }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print environment variable
        run: echo "The value of MY_VARIABLE is $SNOWFLAKE_PASSWORD"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Test dbt
        run: |
          dbt deps
          dbt run 

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy dbt and Airflow DAGs to Dev Server
        run: |
          # Add your deployment script or commands here
          echo "Deploying to development server" 