name: Deploy to Development

on:
  push:
    branches:
      - development

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DBT_SNOWFLAKE_SERVICE_ACCOUNT_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: token-metrics-389311
          export_default_credentials: true

      # - name: Retrieve dbt manifest from GCS 

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'

      # - name: Install dbt
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install dbt-snowflake

      # - name: Run dbt Commands
      #   env:  # Pass the secret as an environment variable
      #     SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      #   run: |
      #     dbt deps 
      #     dbt run 

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy dbt and Airflow DAGs to Dev Server
        run: |
          echo "Deploying to development server"
          # Add your actual deployment commands here
