name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt

      - name: Test dbt
        run: |
          dbt deps
          dbt seed --profiles-dir profiles/prod
          dbt run --profiles-dir profiles/prod
          dbt test --profiles-dir profiles/prod

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy dbt and Airflow DAGs to Prod Server
        run: |
          # Add your deployment script or commands here
          echo "Deploying to production server" 