name: Deploy Airflow/DBT to server

on:
  push:
    branches:
      - development
      - main
    paths:
      #only run if there are changes in dbt folder
      - "dbt/**"
      - ".github/workflows/**"


env:
  # you should channge env to production, but leave it developme
  # ENVIRONMENT: ${{ github.base_ref }}
  # ENVIRONMENT: if [ "${{ github.base_ref }}" == "development" ]; then echo "development"; else echo "production"; fi
        #   env:  # Pass the secret as an environment variable
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

jobs:
  build-and-test-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set ENVIRONMENT variable
        run: |
          cd ..
          if [ "${{ github.event.pull_request.base.ref }}" == "development" ]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          fi
      # Step 2: Write the credentials JSON to a temporary file
      - name: Create credentials file from secret
        run: |
          mkdir -p ./credentials
          echo "${{ secrets.DBT_SNOWFLAKE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./credentials/dbt-snowflake-credentials-sa.json
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: token-metrics-389311  # Replace with your GCP Project ID
      # Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=./credentials/dbt-snowflake-credentials-sa.json
      # - name: Get dbt Manifest
      #   run: |
      #     mkdir state
      #     gcloud storage cp gs://tm-dbt-snowflake/${ENVIRONMENT}/manifest.json ./state/manifest.json || echo "File does not exist. Skipping..."
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake==1.7.5
      - name: Generate manifest file 
        run: |
          echo $ENVIRONMENT
          dbt deps
          dbt docs generate --target ci
      - name: Upload manifest to GCS
        run: |
          gsutil cp target/manifest.json gs://tm-dbt-snowflake/${ENVIRONMENT}/

  deploy-airflow-dbt-to-server:
    runs-on: ubuntu-latest
    needs: build-and-test-dbt
    defaults:
      run:
        working-directory: ./dbt
    steps:


      - name: Checkout code
        uses: actions/checkout@v2

      - name: print environment
        id: check_changes
        run: |
          echo $ENVIRONMENT