name: Deploy Airflow/DBT to server

on:
  push:
    branches:
      - development
      - main
    paths:
      #only run if there are changes in dbt folder
      - "dbt/**"
      - ".github/workflows/**"


env:
  # you should channge env to production, but leave it developme
  # ENVIRONMENT: ${{ github.base_ref }}
  # ENVIRONMENT: if [ "${{ github.base_ref }}" == "development" ]; then echo "development"; else echo "production"; fi
        #   env:  # Pass the secret as an environment variable
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

jobs:
  dbt-ci:
    name: "dbt-slim-ci"
    uses: ./.github/workflows/dbt-slim-ci.yml
    secrets: inherit

  deploy-airflow-dbt-to-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt
    steps:


      - name: Checkout code
        uses: actions/checkout@v2

      - name: print environment
        id: check_changes
        run: |
          echo $ENVIRONMENT